/**
 * Generates the complete TypeScript source file for the plugin registry
 * from validated plugin registry entries.
 *
 * @param {PluginRegistryEntry[]} plugins
 * @returns {string}
 */
export function generateSource(plugins) {
  const entries = plugins
    .map(
      ({ packageName, exportName, displayName, description }) =>
        `  {\n` +
        `    packageName: ${JSON.stringify(packageName)},\n` +
        `    exportName: ${JSON.stringify(exportName)},\n` +
        `    displayName: ${JSON.stringify(displayName)},\n` +
        `    description: ${JSON.stringify(description)},\n` +
        `  },`,
    )
    .join("\n");

  return `// This file is generated by scripts/generate-plugin-registry.mjs.
// Do not edit manually.

export interface TestForgePluginRegistryEntry {
  packageName: string;
  exportName: string;
  displayName: string;
  description: string;
}

export const pluginRegistry: TestForgePluginRegistryEntry[] = [
${entries}
];
`;
}
