import { describe, expect, it } from "vitest";
import { generateSource } from "../generate-source.mjs";

describe("generateSource", () => {
  // TODO fix tests
  /*
  it("should generate an empty plugin registry", () => {
    expect(generateSource([]))
      .toBe(`// This file is generated by scripts/generate-plugin-registry.mjs.
// Do not edit manually.

export interface TestForgePluginRegistryEntry {
  packageName: string;
  exportName: string;
  displayName: string;
  description: string;
}

export const pluginRegistry: TestForgePluginRegistryEntry[] = [

];
`);
  });

  it("should generate a plugin registry entry", () => {
    const plugins = [
      {
        packageName: "@testforgejs/vue-test-plugin-pinia",
        exportName: "piniaPlugin",
        displayName: "Pinia",
        description: "Pinia store integration",
      },
    ];

    expect(generateSource(plugins))
      .toBe(`// This file is generated by scripts/generate-plugin-registry.mjs.
// Do not edit manually.

export interface TestForgePluginRegistryEntry {
  packageName: string;
  exportName: string;
  displayName: string;
  description: string;
}

export const pluginRegistry: TestForgePluginRegistryEntry[] = [
  {
    packageName: "@testforgejs/vue-test-plugin-pinia",
    exportName: "piniaPlugin",
    displayName: "Pinia",
    description: "Pinia store integration",
  },
];
`);
  });

  it("should generate multiple plugin registry entries", () => {
    const plugins = [
      {
        packageName: "@testforgejs/vue-test-plugin-i18n",
        exportName: "i18nPlugin",
        displayName: "Vue I18n",
        description: "Vue I18n integration",
      },
      {
        packageName: "@testforgejs/vue-test-plugin-pinia",
        exportName: "piniaPlugin",
        displayName: "Pinia",
        description: "Pinia store integration",
      },
    ];

    expect(generateSource(plugins))
      .toBe(`// This file is generated by scripts/generate-plugin-registry.mjs.
// Do not edit manually.

export interface TestForgePluginRegistryEntry {
  packageName: string;
  exportName: string;
  displayName: string;
  description: string;
}

export const pluginRegistry: TestForgePluginRegistryEntry[] = [
  {
    packageName: "@testforgejs/vue-test-plugin-i18n",
    exportName: "i18nPlugin",
    displayName: "Vue I18n",
    description: "Vue I18n integration",
  },
  {
    packageName: "@testforgejs/vue-test-plugin-pinia",
    exportName: "piniaPlugin",
    displayName: "Pinia",
    description: "Pinia store integration",
  },
];
`);
  });
  */

  it("should serialize special characters safely", () => {
    const plugins = [
      {
        packageName: '@testforgejs/vue-test-plugin-"test"',
        exportName: "testPlugin",
        displayName: 'Test "Plugin"',
        description: "Integration with a\nspecial character",
      },
    ];

    const source = generateSource(plugins);

    expect(source).toContain(`packageName: "@testforgejs/vue-test-plugin-\\"test\\"",`);
    expect(source).toContain(`displayName: "Test \\"Plugin\\"",`);
    expect(source).toContain(`description: "Integration with a\\nspecial character",`);
  });

  /*
  it("should preserve plugin order", () => {
    const plugins = [
      {
        packageName: "@testforgejs/vue-test-plugin-router",
        exportName: "routerPlugin",
        displayName: "Vue Router",
        description: "Vue Router integration",
      },
      {
        packageName: "@testforgejs/vue-test-plugin-vuetify",
        exportName: "vuetifyPlugin",
        displayName: "Vuetify",
        description: "Vuetify integration",
      },
    ];

    const source = generateSource(plugins);

    expect(source.indexOf("routerPlugin")).toBeLessThan(source.indexOf("vuetifyPlugin"));
  });
  */
});
